name: Scan NuGet Vulnerabilities

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch: # Allow manual triggering of the workflow
    schedule:
    - cron: '0 3 * * 1'   # every Monday at 3 AM UTC

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x' # Use the latest .NET 8.0 SDK

            - name: Restore dependencies
              run: dotnet restore

            - name: Check for vulnerable packages
              id: check-vuln
              run: |
                OUTPUT=$(dotnet list package --vulnerable --include-transitive --format json)
                echo "$OUTPUT"
                VULN_COUNT=$(echo "$OUTPUT" | jq '[.projects[].vulnerable[]?] | length')
                if [ "$VULN_COUNT" -gt 0 ]; then
                  echo "Found $VULN_COUNT vulnerable packages!"
                  echo "vulnerable=true" >> $GITHUB_OUTPUT
                  exit 1
                else
                  echo "No vulnerable packages found."
                  echo "vulnerable=false" >> $GITHUB_OUTPUT
                fi

                
        